CREATE TABLE IF NOT EXISTS {{ .prefix }}_users (
  id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY (INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1),
  password character varying(128) NOT NULL,
  last_login timestamp with time zone,
  is_superuser boolean NOT NULL,
  username character varying(150) NOT NULL,
  first_name character varying(150) NOT NULL,
  last_name character varying(150) NOT NULL,
  email character varying(254) NOT NULL,
  created_at timestamp with time zone NOT NULL,
  CONSTRAINT {{ .prefix }}_users_user_pkey PRIMARY KEY (id),
  CONSTRAINT {{ .prefix }}_users_user_username_key UNIQUE (username)
);
---- create above / drop below ----
DROP TABLE {{.prefix}}_users