CREATE TABLE IF NOT EXISTS {{ .prefix }}_teams (
  id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY (INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1),
  name character varying(150) NOT NULL,
  created_at timestamp with time zone NOT NULL DEFAULT NOW(),
  CONSTRAINT {{ .prefix }}_teams_team_pkey PRIMARY KEY (id),
  CONSTRAINT {{ .prefix }}_teams_team_name_key UNIQUE (name)
);
---- create above / drop below ----
DROP TABLE {{ .prefix }}_teams