CREATE TABLE IF NOT EXISTS {{ .prefix }}_work_items (
  id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY (INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1),
  reported_by bigint NOT NULL, 
  assigned_to bigint,
  name character varying(256) NOT NULL,
  description character varying,
  child_items bigint[],
  comments bigint[],
  created_at timestamp with time zone NOT NULL DEFAULT NOW(),
  CONSTRAINT {{ .prefix }}_work_items_item_pkey PRIMARY KEY (id)
);
---- create above / drop below ----
DROP TABLE {{ .prefix }}_work_items