CREATE TABLE IF NOT EXISTS {{ .prefix }}_work_item_comments (
  id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY (INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1),
  reported_by bigint NOT NULL, 
  description character varying,
  child_items bigint[],
  created_at timestamp with time zone NOT NULL DEFAULT NOW(),
  CONSTRAINT {{ .prefix }}_work_item_comments_comment_pkey PRIMARY KEY (id)
);
---- create above / drop below ----
DROP TABLE {{ .prefix }}_work_item_comments